apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      imagePullSecrets:
      - name: regcred         
      containers:
      - name: hello-go
        image: mkarakas/hello-world-private
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
