apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: mkarakas/hello-world:go
        livenessProbe: 
            httpGet:
              path: /live
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10           
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 6060
