apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: mkarakas/hello-world:go
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 6060

---

apiVersion: v1
kind: Service
metadata:
  name: hello-go
spec:
  type:  NodePort
  selector:
    app: hellogo
  ports:
  - port: 80
    targetPort: 6060
    nodePort: 32060

